version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=deger
      - POSTGRES_DB=unknown_db
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
    container_name: db

volumes:
  postgres-data:
